language: cpp
git:
  depth: 1
env:
  global:
    - BYOND_MAJOR="511"
    - BYOND_MINOR="1385"
cache:
  directories:
    - $HOME/BYOND-${BYOND_MAJOR}.${BYOND_MINOR}
addons:
  apt:
    packages:
      - libc6-i386
      - libstdc++6:i386
services:
  - mysql
install:
  - git clone --depth=1 https://github.com/MariaDB/mariadb-connector-c
  - cd mariadb-connector-c && cmake . && make libmariadb && cd ..
script:
  - mkdir artifacts && cd artifacts && cmake .. && make test && cd ..
  - mv mariadb-connector-c/libmariadb/libmariadb.so tests/ && cp artifacts/BSQL.so tests/
  - cd tests && ./test_byond.sh
