language: cpp
git:
  depth: 1
env:
  global:
    - BYOND_MAJOR="511"
    - BYOND_MINOR="1385"
cache:
  directories:
    - $HOME/BYOND-${BYOND_MAJOR}.${BYOND_MINOR}
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7
      - gcc-7-multilib
env:
  - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
services:
  - mysql
install:
  - eval "${MATRIX_EVAL}"
  - git clone --depth=1 https://github.com/MariaDB/mariadb-connector-c
  - cd mariadb-connector-c && cmake . -D CMAKE_C_FLAGS="-m32" && make install && cd ..
script:
  - mkdir artifacts && cd artifacts && cmake .. -DCMAKE_CXX_FLAGS="-m32" && make test && cd ..
  - cp artifacts/BSQL.so tests/
  - cd tests && ./test_byond.sh
