language: cpp
git:
  depth: 1
env:
  global:
    - BYOND_MAJOR="511"
    - BYOND_MINOR="1385"
cache:
  directories:
    - $HOME/BYOND-${BYOND_MAJOR}.${BYOND_MINOR}
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7
      - gcc-7-multilib
      - g++-7-multilib
      - libc6-i386
      - libstdc++6:i386
      - libmariadbclient-dev:i386
env:
  - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
services:
  - mysql
install:
  - eval "${MATRIX_EVAL}"
script:
  - mkdir artifacts && cd artifacts && cmake .. && make && cd ..
  - cp artifacts/BSQL/BSQL.so tests/
  - cd tests && ./test_byond.sh
