language: cpp
git:
  depth: 1
env:
  global:
    - BYOND_MAJOR="511"
    - BYOND_MINOR="1385"
cache:
  directories:
    - $HOME/BYOND-${BYOND_MAJOR}.${BYOND_MINOR}
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7
      - gcc-7-multilib
      - linux-libc-dev:i386
      - libstdc++6:i386
      - libssl-dev:i386
env:
  - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
services:
  - mysql
install:
  - eval "${MATRIX_EVAL}"
script:
  - mkdir artifacts && cd artifacts && export LDFLAGS=-m32 && cmake .. -DCMAKE_C_FLAGS="-m32" -DCMAKE_CXX_FLAGS="-m32" && make test && cd ..
  - cp artifacts/BSQL.so tests/
  - cd tests && ./test_byond.sh
