language: cpp
git:
  depth: 1
env:
  global:
    - BYOND_MAJOR="511"
    - BYOND_MINOR="1385"
cache:
  directories:
    - $HOME/BYOND-${BYOND_MAJOR}.${BYOND_MINOR}
addons:
  apt:
    packages:
      - cmake
      - libc6-i386
      - libstdc++6:i386
      - libmariadb-dev
services:
  - mysql
script:
  - mkdir artifacts && cd artifacts && cmake .. && make test
  - cd tests && ./test_byond.sh
